version: "3.8"

services:
  svelte-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro # For the live update if you want
    environment:
      NODE_ENV: production